# Development configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotelbooker
    username: root
    password: Admin
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.hotelbooker: DEBUG
    org.springframework.security: DEBUG

# Stripe Configuration
stripe:
  api-key: "${STRIPE_SECRET_KEY:sk_test_YOUR_SECRET_KEY_HERE}"
  publishable-key: "${STRIPE_PUBLISHABLE_KEY:pk_test_YOUR_PUBLISHABLE_KEY_HERE}"
  webhook-secret: "${STRIPE_WEBHOOK_SECRET:}"  # Will be set when webhook is configured
