# Development configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotelbooker
    username: root
    password: Admin
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.hotelbooker: DEBUG
    org.springframework.security: DEBUG
