spring:
  application:
    name: hotel-booking-system
  
  datasource:
    url: jdbc:postgresql://localhost:5432/hotelbooker
    username: root
    password: Admin
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

server:
  port: 8080
  servlet:
    context-path: /api/v1

# JWT Configuration
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds

# CORS Configuration
cors:
  allowed-origins: http://localhost:*,http://127.0.0.1:*
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Logging
logging:
  level:
    com.hotelbooker: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

# Stripe Configuration
stripe:
  api-key: "${STRIPE_SECRET_KEY:sk_test_YOUR_SECRET_KEY_HERE}"
  publishable-key: "${STRIPE_PUBLISHABLE_KEY:pk_test_YOUR_PUBLISHABLE_KEY_HERE}"
  webhook-secret: "${STRIPE_WEBHOOK_SECRET:}"  # Will be set when webhook is configured
